#!/usr/bin/env zsh

# If DOTY_DIRECTORY is not defined, use the current script's directory.
[[ -z "${DOTY_DIRECTORY}" ]] && export DOTY_DIRECTORY="${${(%):-%x}:a:h}"

[[ -z "${DOTFILES_LOCAL_DIRECTORY}" ]] && export DOTFILES_LOCAL_DIRECTORY="${DOTY_DIRECTORY}.local"
[[ -z "${DOTY_DEVELOPMENT_DIRECTORY}" ]] && export DOTY_DEVELOPMENT_DIRECTORY="${HOME}/.local/share"
[[ -z "${DOTY_DEVELOPMENT_CACHE_DIRECTORY}" ]] && export DOTY_DEVELOPMENT_CACHE_DIRECTORY="${HOME}/.local/cache"
[[ -z "${DOTY_DEVELOPMENT_SDK_DIRECTORY}" ]] && export DOTY_DEVELOPMENT_SDK_DIRECTORY="${DOTY_DEVELOPMENT_DIRECTORY}/sdks"

[[ -d "${DOTY_DEVELOPMENT_DIRECTORY}" ]] || mkdir -p "${DOTY_DEVELOPMENT_DIRECTORY}"
[[ -d "${DOTY_DEVELOPMENT_CACHE_DIRECTORY}" ]] || mkdir -p "${DOTY_DEVELOPMENT_CACHE_DIRECTORY}"
[[ -d "${DOTY_DEVELOPMENT_SDK_DIRECTORY}" ]] || mkdir -p "${DOTY_DEVELOPMENT_SDK_DIRECTORY}"

# Load the local shell dotfiles, and then some:
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/path" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/path"
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/bash_prompt" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/bash_prompt"
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/bash_exports" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/bash_exports"
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/aliases" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/aliases"
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/bash_functions" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/bash_functions"
[[ -f "${DOTFILES_LOCAL_DIRECTORY}/extra" ]] && source "${DOTFILES_LOCAL_DIRECTORY}/extra"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
if [[ -z $plugins ]]; then
    plugins=(
        adb
        aliases
        brew
        colored-man-pages
        colorize
        command-not-found
        copyfile
        copypath
        cve
        dotenv
        emoji
        emotty
        extract
        fd
        git
        git-extras
        # git-prompt
        gitignore
        history
        jsontools
        last-working-dir
        limactl
        # mise
        nmap
        nodenv
        npm
        nvm
        # pop
        pre-commit
        # pyenv
        # pylint
        ripgrep
        sdk
        thefuck
        # themes
        urltools
        vscode
        z

        ### Local
        android
        encode64
        fzf
        github
        golang
        kubectl
        kubectx
        macos
        minikube
        nodejs
        podman
        python
        rust
        tmux

        gcloud
        doty
        zsh-autosuggestions
        zsh-syntax-highlighting
    )
fi

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell" # set by `omz`
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="%F $(tput setaf 136)...$(tput sgr0)%f"

# Path to your oh-my-zsh installation.
export ZSH="${DOTY_DIRECTORY}/libraries/oh-my-zsh"
export ZSH_CACHE_DIR="${DOTY_DEVELOPMENT_CACHE_DIRECTORY}/oh-my-zsh"
# Would you like to use another custom folder than $ZSH/custom?
export ZSH_CUSTOM="${DOTY_DIRECTORY}"

export ZSHZ_DATA="${DOTY_DEVELOPMENT_CACHE_DIRECTORY}/z/.z"

export ZSH_DOTENV_FILE=".envrc"

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#777777,bg=#0f3000"
export ZSH_AUTOSUGGEST_STRATEGY="match_prev_cmd"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

source "${ZSH}/oh-my-zsh.sh"

# Load the local shell dotfiles, and then some:
[[ -f "${HOME}/.zsh_path" ]] && source "${HOME}/.zsh_path"
[[ -f "${HOME}/.zsh_prompt" ]] && source "${HOME}/.zsh_prompt"
[[ -f "${HOME}/.zsh_exports" ]] && source "${HOME}/.zsh_exports"
[[ -f "${HOME}/.zsh_aliases" ]] && source "${HOME}/.zsh_aliases"
[[ -f "${HOME}/.zsh_functions" ]] && source "${HOME}/.zsh_functions"
[[ -f "${HOME}/.zsh_extra" ]] && source "${HOME}/.zsh_extra"
