DOTY_DEVELOPMENT_DIRECTORY="${HOME}/.dev"
DOTY_DEVELOPMENT_SDK_DIRECTORY="${DOTY_DEVELOPMENT_DIRECTORY}/sdks"
DOTY_DEVELOPMENT_CACHE_DIRECTORY="${DOTY_DEVELOPMENT_DIRECTORY}/.cache"

GITHUB_PERSONAL_TOKEN_RO=

unset DOTY_DEVELOPMENT_DIRECTORY
unset DOTY_DEVELOPMENT_SDK_DIRECTORY
unset DOTY_DEVELOPMENT_CACHE_DIRECTORY