return {
    icons = {
        file = "",
        module = "",
        namespace = "",
        package = "",
        class = "",
        method = "",
        property = "",
        field = "",
        constructor = "",
        enum = "",
        interface = "",
        fn = "",
        variable = "",
        constant = "",
        string = "",
        number = "",
        boolean = "",
        array = "",
        object = "",
        key = "",
        null = "",
        enumMember = "",
        struct = "",
        event = "",
        operator = "",
        typeParameter = ""
    }
}
